# Generated by Django 5.2.10 on 2026-03-30 14:39

from django.db import migrations, models


def _coalesce_time_charfields(apps, schema_editor):
    """Remplace les NULL par '' avant de retirer null=True (PostgreSQL / TimescaleDB)."""
    if schema_editor.connection.vendor != "postgresql":
        return
    table = "weather_quotidienne"
    fields = ("htn", "htx", "hxy", "hxi", "hxi2", "hxi3s")
    with schema_editor.connection.cursor() as cursor:
        sets = ", ".join(f'"{f}" = COALESCE("{f}", \'\')' for f in fields)
        cursor.execute(f"UPDATE {table} SET {sets}")


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0002_timescaledb_hypertables"),
    ]

    operations = [
        migrations.RunPython(_coalesce_time_charfields, _noop_reverse),
        migrations.AlterField(
            model_name="quotidienne",
            name="htn",
            field=models.CharField(
                blank=True, default="", help_text="Time of min (HHMM)", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="quotidienne",
            name="htx",
            field=models.CharField(
                blank=True, default="", help_text="Time of max (HHMM)", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="quotidienne",
            name="hxi",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AlterField(
            model_name="quotidienne",
            name="hxi2",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AlterField(
            model_name="quotidienne",
            name="hxi3s",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AlterField(
            model_name="quotidienne",
            name="hxy",
            field=models.CharField(
                blank=True, default="", help_text="Time of max gust", max_length=4
            ),
        ),
    ]
